### ISSUE TITLE
Problem on linuxmint 18

### ISSUE THREAD

**Issue by r06625030** [DIGImend/uclogic-tools#8]
I use linuxmint 18, after ran uclogic-probe and uclogic-decode, the cursor deviates and my pen even lost the function of left click.
This is my output of `sudo lsusb -v`:
```
Bus 001 Device 002: ID 5543:0046 UC-Logic Technology Corp. 
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               1.10
  bDeviceClass            0 (Defined at Interface level)
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x5543 UC-Logic Technology Corp.
  idProduct          0x0046 
  bcdDevice            0.00
  iManufacturer           5 UC-Logic
  iProduct                6 ARTISUL D13S
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           84
    bNumInterfaces          3
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              100mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     190
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               5
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     183
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               4
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 No Subclass
      bInterfaceProtocol      0 None
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      92
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               8
Device Status:     0x0000
  (Bus Powered)
```

**Comment by spbnick** [comment]
Hi @r06625030, `uclogic-probe` is a debugging and a development tool. It's not supposed to make it work, and if any tablet does work after it's executed, then it's mostly a happy coincidence. Your tablet will need proper support in a kernel driver to work.

**Comment by r06625030** [comment]
Thank you for reminding me. Now I have another problem, I tried digimend-kernel-drivers, after I execute the command`sudo modprobe -r hid-kye hid-uclogic hid-polostar hid-viewsonic`, it doesn't work, so I reboot my computer, then it goes to a black screen with blinking cursor. How can I fix it?

**Comment by spbnick** [comment]
You might be hitting https://github.com/DIGImend/digimend-kernel-drivers/issues/250 which is fixed in the latest development version.

**Comment by r06625030** [comment]
Should I uninstall the version I am currently using first?

**Comment by spbnick** [comment]
@r06625030, it's better to uninstall first.

**Comment by r06625030** [comment]
Sorry for the too late reply. I tried the latest development version, it no longer turns black screen, but it still doesn't work, maybe it can't support ARTISUL D13S?

**Comment by spbnick** [comment]
As far as I know, that tablet is not supported yet. Look for an issue requesting support for it. If you find it, add a thumbs-up reaction to it, so I can see its popularity and pick it earlier. If you can't find an issue for your tablet, create one and provide diagnostics.

**Comment by r06625030** [comment]
Thank you! I have created an [issue](https://github.com/DIGImend/digimend-kernel-drivers/issues/267) about its diagnostics.
